#!/bin/sh
# generated by csub-broker 0.1.0 for job csub-demo; do not edit
export PATH=/usr/local/bin:/usr/bin:/bin USER=testuser HOME=/home/u
JOB_DIR=/home/u/.csub/jobs/"$LSB_JOBID"
mkdir -p "$JOB_DIR" && cd "$JOB_DIR" || exit 97
SCRATCH=''
/home/u/.local/pipx/venvs/csub/bin/python -m csub.broker --serve "$JOB_DIR/csub.sock" &
BROKER_PID=$!
trap 'kill "$BROKER_PID" 2>/dev/null' EXIT
i=0; while [ ! -S "$JOB_DIR/csub.sock" ]; do i=$((i + 1)); [ "$i" -gt 100 ] && exit 93; sleep 0.1; done
/home/u/.local/share/csub/agentic-sandbox/scripts/podman-run.sh \
    --keep-id \
    --image ghcr.io/test/agent:latest \
    --rw <P0> \
    --ro <P1> \
    --ro "$JOB_DIR/csub.sock" \
    -- /bin/sh -c 'set -u
export HOME=<P0>/.csub/home
J=<P0>/.csub/jobs/"$1"
export USER=testuser LOGNAME=testuser LSB_JOBID="$1"
export CSUB_TRANSPORT=unix CSUB_SOCKET="$6" CSUB_JOB_ID="$1"
export CSUB_SESSION=testsess CSUB_IMAGE=ghcr.io/test/agent:latest
export CSUB_MOUNTS=<P0>:rw,<P1>:ro
export CSUB_WALLTIME_MIN=60 CSUB_DEADLINE_EPOCH=$(($5 + 3600))
[ -n "$2" ] && export CUDA_VISIBLE_DEVICES="$2"
[ -n "$3" ] && export TMPDIR="$3"
[ -n "$4" ] && export LSB_DJOB_NUMPROC="$4"
mkdir -p "$J" "$HOME" || exit 96
cd <P0> || exit 95
exec sh -c '"'"'echo hi'"'"' >"$J/stdout" 2>"$J/stderr"
' csub-job "$LSB_JOBID" "${CUDA_VISIBLE_DEVICES:-}" "$SCRATCH" "${LSB_DJOB_NUMPROC:-}" "$(date +%s)" "$JOB_DIR/csub.sock"
rc=$?
[ -n "$SCRATCH" ] && rm -rf "$SCRATCH"
echo "$rc" > "$JOB_DIR/exit_code"
exit "$rc"
